[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
edition = "2018"
name = "lexer"
version = "0.1.0"

[[bench]]
harness = false
name = "bench"

[dependencies]
smallvec = "0.6.10"

[dev-dependencies]
criterion = "0.2"

[lib]
bench = false
